name: Run gersemi
description: Runs gersemi and checks for any changes introduced by it

inputs:
  failCondition:
    description: Controls whether failed checks also fail the workflow run
    required: false
    default: never
  workingDirectory:
    description: Working directory for checks
    required: false
    default: ${{ github.workspace }}

runs:
  using: composite
  steps:
    # ✅ Block Windows runners early
    - name: Check Runner Operating System 🏃‍♂️
      if: runner.os == 'Windows'
      shell: bash
      run: |
        echo "::notice::run-gersemi action requires a macOS-based or Linux-based runner."
        exit 0

    # ✅ Check for changed files
    - name: Check for Changed Files ✅
      uses: ./.github/actions/check-changes
      id: checks
      with:
        checkGlob: "'*.cmake' '*CMakeLists.txt'"
        diffFilter: 'ACM'

    # ✅ Install dependencies (zsh + brew setup)
    - name: Install Dependencies 🛍️
      if: runner.os == 'Linux' && fromJSON(steps.checks.outputs.hasChangedFiles)
      shell: bash
      run: |
        echo ::group::Install Dependencies
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
        brew install --quiet zsh obsproject/tools/gersemi
        echo ::endgroup::

    # ✅ Run gersemi check (non-blocking)
    - name: Run gersemi 🎛️
      if: fromJSON(steps.checks.outputs.hasChangedFiles)
      id: gersemi-check
      shell: bash
      working-directory: ${{ github.workspace }}
      env:
        CHANGED_FILES: ${{ steps.checks.outputs.changedFiles }}
      run: |
        echo ::group::Run gersemi check
        changes=$(echo "${CHANGED_FILES}" | tr -d '[]"\'' | tr ',' ' ')
        echo "Checking formatting for: $changes"
        gersemi --check $changes || echo "⚠ Formatting issues detected"
        echo ::endgroup::

    # ✅ Auto-fix regardless of check result
    - name: Auto-fix gersemi
      if: fromJSON(steps.checks.outputs.hasChangedFiles)
      shell: bash
      working-directory: ${{ github.workspace }}
      env:
        CHANGED_FILES: ${{ steps.checks.outputs.changedFiles }}
      run: |
        echo ::group::Auto-fix gersemi
        changes=$(echo "${CHANGED_FILES}" | tr -d '[]"\'' | tr ',' ' ')
        gersemi --in-place $changes
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add $changes
        git commit -m "Apply gersemi auto-fix" || echo "No changes to commit"
        git push || echo "Push skipped"
        echo ::endgroup::