name: Run clang-format
description: Runs clang-format and checks for any changes introduced by it

inputs:
  failCondition:
    description: Controls whether failed checks also fail the workflow run
    required: false
    default: never
  workingDirectory:
    description: Working directory for checks
    required: false
    default: ${{ github.workspace }}

runs:
  using: composite
  steps:
    # ✅ Block Windows runners early
    - name: Check Runner Operating System 🏃‍♂️
      if: runner.os == 'Windows'
      shell: bash
      run: |
        echo "::notice::run-clang-format action requires a macOS-based or Linux-based runner."
        exit 0

    # ✅ Check for changed files
    - name: Check for Changed Files ✅
      uses: ./.github/actions/check-changes
      id: checks
      with:
        checkGlob: "'*.cpp' '*.hpp' '*.h' '*.c'"
        diffFilter: 'ACM'

    # ✅ Install dependencies (clang-format)
    - name: Install Dependencies 🛍️
      if: runner.os == 'Linux' && fromJSON(steps.checks.outputs.hasChangedFiles)
      shell: bash
      run: |
        echo ::group::Install Dependencies
        sudo apt-get update
        sudo apt-get install -y clang-format
        echo ::endgroup::

    # ✅ Run clang-format check (non-blocking)
    - name: Run clang-format 🐉
      if: fromJSON(steps.checks.outputs.hasChangedFiles)
      id: clang-format-check
      shell: bash
      working-directory: ${{ github.workspace }}
      env:
        CHANGED_FILES: ${{ steps.checks.outputs.changedFiles }}
      run: |
        echo ::group::Run clang-format check
        changes=$(echo "${CHANGED_FILES}" | tr -d '[]"\'' | tr ',' ' ')
        echo "Checking formatting for: $changes"
        for file in $changes; do
          clang-format --dry-run --Werror "$file" || echo "⚠ Formatting issue in $file"
        done
        echo ::endgroup::

    # ✅ Auto-fix regardless of check result
    - name: Auto-fix clang-format
      if: fromJSON(steps.checks.outputs.hasChangedFiles)
      shell: bash
      working-directory: ${{ github.workspace }}
      env:
        CHANGED_FILES: ${{ steps.checks.outputs.changedFiles }}
      run: |
        echo ::group::Auto-fix clang-format
        changes=$(echo "${CHANGED_FILES}" | tr -d '[]"\'' | tr ',' ' ')
        for file in $changes; do
          clang-format -i "$file"
        done
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add $changes
        git commit -m "Apply clang-format auto-fix" || echo "No changes to commit"
        git push || echo "Push skipped"
        echo ::endgroup::