name: Run gersemi
description: Runs gersemi and checks for any changes introduced by it

inputs:
  failCondition:
    description: Controls whether failed checks also fail the workflow run
    required: false
    default: never
  workingDirectory:
    description: Working directory for checks
    required: false
    default: ${{ github.workspace }}

runs:
  using: composite
  steps:
    # ✅ Block Windows runners early
    - name: Check Runner Operating System 🏃‍♂️
      if: runner.os == 'Windows'
      shell: bash
      run: |
        echo "::notice::run-gersemi action requires a macOS-based or Linux-based runner."
        exit 2

    # ✅ Check for changed files
    - name: Check for Changed Files ✅
      uses: ./.github/actions/check-changes
      id: checks
      with:
        checkGlob: "'*.cmake' '*CMakeLists.txt'"
        diffFilter: 'ACM'

    # ✅ Install dependencies (zsh + brew setup)
    - name: Install Dependencies 🛍️
      if: runner.os == 'Linux' && fromJSON(steps.checks.outputs.hasChangedFiles)
      shell: bash
      run: |
        echo ::group::Install Dependencies
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
        brew install --quiet zsh
        echo ::endgroup::

    # ✅ Run gersemi with explicit zsh call
    - name: Run gersemi 🎛️
      if: fromJSON(steps.checks.outputs.hasChangedFiles)
      id: result
      shell: bash
      working-directory: ${{ github.workspace }}
      env:
        CHANGED_FILES: ${{ steps.checks.outputs.changedFiles }}
      run: |
        echo ::group::Install gersemi
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew install --quiet obsproject/tools/gersemi
        echo ::endgroup::

        echo ::group::Run gersemi
        chmod +x build-aux/run-gersemi build-aux/.run-format.zsh
        changes=$(echo "${CHANGED_FILES}" | tr -d '[]"\'' | tr ',' ' ')
        zsh ./build-aux/run-gersemi --fail-${{ inputs.failCondition }} --check ${changes}
        echo ::endgroup::